### ISSUE TITLE
Configurable remote

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf-push-action#10]
We need to make the remote configurable so that users can choose to authenticate with a remote other than buf.build ([here](https://github.com/bufbuild/buf-push-action/blob/6747ce6c58c63b7627804970bd42f88498c050ae/src/run.ts#L84)).

We _could_ add a `remote` input to [action.yml](https://github.com/bufbuild/buf-push-action/blob/main/action.yml#L7) and use `buf registry login <$remote> --username <$placeholder> --token-stdin` command, so that we don't need to manually write the `.netrc` file, too. The username would be unused for this action since it's not actually required for BSR authentication (just the Go Module Proxy for now).

Alternatively (and preferably), we could refactor all of the actions that  and simply provide the `BUF_TOKEN` environment variable to each `buf` command so that it remains agnostic to the `remote` (re: https://github.com/bufbuild/buf-setup-action/pull/4#issuecomment-951035834).

The buf_token input is already configured here, so we should be able to update this behavior and extend what remotes we support while maintaining compatibility. For reference, this solution applies to both [buf-lint-action](https://github.com/bufbuild/buf-lint-action/blob/f5029cc05a2a5d95c2edc7d203e4efce0a3b65ed/action.yml#L13) and [buf-breaking-action](https://github.com/bufbuild/buf-breaking-action/blob/4280330ef4fe7f88fd94967c9ac496b3ac0d71c8/action.yml#L24), too.

**Comment by oliversun09** [comment]
Pushing to custom remote is achieved by setting `name` in `buf.yaml`, and `buf push` pushes the module that remote. To confirm, I created a git repo on GitHub, containing a Buf module with `buf.yaml`, in which the remote is set to the testing remote. I set up the action, made some change and pushed to GitHub. The change showed up in the bsr on that remote as well.
