### ISSUE TITLE
Breaking change introduced in `v1.1.0`

### ISSUE THREAD

**Issue by KenxinKun** [bufbuild/buf-push-action#26]
Hi buf team, with last week's release of `v1.1.0` I believe a breaking change was introduced that has made our CI stop pushing to BSR. In particular:
```
if [ "${GITHUB_REF_TYPE}" != "branch" ]; then
  echo "reference type is not branch, skipping" >&2
  exit 0
fi
```
This is skipping for us, since in our workflow we don't push on branch, but for particularly formatted tags on `master` 🤔 

In the interim, I've reverted our GHA workflow to specifically use `v1.0.1` instead of `v1` but of course we'd love to keep up with the latest changes.

My questions are:
- Was this an intended breaking change?
- Can we get a fix or an option to bypass the check?

Thanks!

**Comment by elliotmjackson** [comment]
Hi @KenxinKun! thanks for raising this, sorry we have disrupted you - this is never our intention. Give me a bit to triage this and get back to you with an answer.
