### ISSUE TITLE
Inconsistencies with `buf_token`

### ISSUE THREAD

**Issue by ghost** [bufbuild/buf-push-action#30]
This was reported in the Slack channel.
1. The documentation claims the default value for `buf_token` is `${{github.token}}`. This seems incorrect.
2. It seems that there is some inconsistency between some of the GitHub Actions. [`buf-setup-action`](https://github.com/bufbuild/buf-setup-action#input) uses the name `buf_api_token` whereas this and some other actions use `buf_token`. We should probably unify these at some point?

**Comment by emcfarlane** [comment]
Please see [`buf-action`](https://github.com/bufbuild/buf-action) config. Consolidated to `token`.
