### ISSUE TITLE
Should this action support `with.branch`?

### ISSUE THREAD

**Issue by negz** [bufbuild/buf-push-action#34]
The buf docs indicate that branches have replaced drafts. They show an example of using branches with this action:

https://buf.build/docs/bsr/module/configure#publishing-branches

Yet AFAICT action doesn't have a `with.branch` option. It only has `with.draft`.

**Comment by doriable** [comment]
Yes, this action should support `with.branch`, we are currently in the process of moving our workflows towards branches, so we have not quite updated this action yet.
We will be putting out `branch` support with the action soon! :)

**Comment by phisco** [comment]
@doriable, any update on this? Can we help?

**Comment by emcfarlane** [comment]
The new [`buf-action`](https://github.com/bufbuild/buf-action) has been released to support many of the new features with the v2 config. For push, it will automatically label the commit with the correct git-metadata and keep your branches in sync with the BSR. Please take a look!
